# [Python para computación científica 🚀](https://cpp-review-dune.github.io/tutorial/python)

## NumPy, aspectos del cálculo del arreglo N-dimensional

<!--
## Introducción a la programación orientada a objetos
Metodología: range(inicio, fin, paso).

- Explicar más el for que el rango en sí.
- Moderar el chat cuando hay varias personas.
- Tipos de datos: array de NumPy (reformulación o generalización) o array de Python.
- Independizar Python, es un conjunto de librerías construidas sobre python y su objetivo es graficar.
- Más estructura de las funciones o del tema de la clase.
-->



In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


## [`hello.py`](https://github.com/python/cpython/blob/main/Tools/freeze/hello.py)

In [ ]:
import __hello__

Hello world!


In [ ]:
!(pwd) # Revisar el entorno Ubuntu Bionic 18.04 LTS
!(apt update)

/content
Get:1 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease [3,626 B]
Ign:2 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Hit:5 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:6 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:8 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Get:9 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [83.3 kB]
Hit:11 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Hit:12 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Get:13 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1,554 kB]
Get:14 http://arc

In [ ]:
!(apt install neofetch -y)

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'apt autoremove' to remove it.
The following NEW packages will be installed:
  neofetch
0 upgraded, 1 newly installed, 0 to remove and 8 not upgraded.
Need to get 74.8 kB of archives.
After this operation, 365 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 neofetch all 3.4.0-1 [74.8 kB]
Fetched 74.8 kB in 0s (245 kB/s)
Selecting previously unselected package neofetch.
(Reading database ... 123941 files and directories currently installed.)
Preparing to unpack .../neofetch_3.4.0-1_all.deb ...
Unpacking neofetch (3.4.0-1) ...
Setting up neofetch (3.4.0-1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...


In [ ]:
!(neofetch)

            .-/+oossssoo+/-. 
        `:+ssssssssssssssssss+:` 
      -+ssssssssssssssssssyyssss+- 
    .ossssssssssssssssssdMMMNysssso. 
   /ssssssssssshdmmNNmmyNMMMMhssssss/ 
  +ssssssssshmydMMMMMMMNddddyssssssss+ 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/ 
.ssssssssdMMMNhsssssssssshNMMMdssssssss. 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+ 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+ 
.ssssssssdMMMNhsssssssssshNMMMdssssssss. 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/ 
  +sssssssssdmydMMMMMMMMddddyssssssss+ 
   /ssssssssssshdmNNNNmyNMMMMhssssss/ 
    .ossssssssssssssssssdMMMNysssso. 
      -+sssssssssssssssssyyyssss+- 
        `:+ssssssssssssssssss+:` 
            .-/+oossssoo+/-. 
root@0f74310bf72d 
----------------- 
OS: Ubuntu 18.04.6 LTS x86_64 
Host: Google Compute Engine 
Kernel: 5.10.133+ 
Uptime: 40 secs 
Packages: 1250 
Shell: bash 4.4.20 
CPU: AMD EPYC 7B12 (2) @ 2.249GHz 
Memory: 617MiB / 12985MiB 


In [ ]:
print?

In [ ]:
?

In [ ]:
# Probar el entorno
f = open('/content/sample_data/california_housing_test.csv', 'r')
# Crea una secuencia de números del 0 al 9.
for i in range(10):
  str_line = f.readline()
  print(str_line)
f.close()

"longitude","latitude","housing_median_age","total_rooms","total_bedrooms","population","households","median_income","median_house_value"

-122.050000,37.370000,27.000000,3885.000000,661.000000,1537.000000,606.000000,6.608500,344700.000000

-118.300000,34.260000,43.000000,1510.000000,310.000000,809.000000,277.000000,3.599000,176500.000000

-117.810000,33.780000,27.000000,3589.000000,507.000000,1484.000000,495.000000,5.793400,270500.000000

-118.360000,33.820000,28.000000,67.000000,15.000000,49.000000,11.000000,6.135900,330000.000000

-119.670000,36.330000,19.000000,1241.000000,244.000000,850.000000,237.000000,2.937500,81700.000000

-119.560000,36.510000,37.000000,1018.000000,213.000000,663.000000,204.000000,1.663500,67000.000000

-121.430000,38.630000,43.000000,1009.000000,225.000000,604.000000,218.000000,1.664100,67000.000000

-120.650000,35.480000,19.000000,2310.000000,471.000000,1341.000000,441.000000,3.225000,166900.000000

-122.840000,38.400000,15.000000,3080.000000,617.000000,144

### Python

Python es un lenguaje de programación, interpretado, de alto nivel y propósito general, además de ser un proyecto libre y de código abierto, con una comunidad enorme implicada en el desarrollo y mantenimiento de librerías que hacen posible el *multidominio* actual de Python.

Dada su concepción como lenguaje de propósito general, Python es utilizado en una diversidad de aplicaciones,
desde desarrollo web, encriptación, análisis de datos, procesamiento de imágenes, aprendizaje automático,
computación simbólica, etc.  

Las características de este lenguaje le hacen propicio para el prototipado de aplicaciones, dado que es muy
sencillo y rápido revisar y modificar el código desarrollado. Otra característica muy notable de Python
es su sintaxis simple y fácil de aprender, lo cual ayuda al momento de introducirse en el desarrollo de
algoritmos o el mundo propio de la programación de computadoras.

### Instalando Python

En estos apuntes se utilizará la distribución Google Colab,  opcionalmente puede instalar Anaconda de Python,
a fin de tener el intérprete y las librerías del *core* a completa disposición, porque incluye la mayoría de
librerías utilizadas para el desarrollo de aplicaciones de corte técnico-científico.

### Operaciones Aritméticas Básicas

A partir de este momento puede ingresar código Python en las celdas y teclear **Shift + Enter** para ejecutar la instrucción y la celda le devolverá lo que resulte de esto. Por ejemplo, si escribe un número cualesquiera y presiona la combinación indicada, la consola le devolverá justamente el mismo número:

In [ ]:
# ()**,*,/,+,-
12 + 8

20

In [ ]:
12**2

144

In [ ]:
2 ** 0.5

1.4142135623730951

In [ ]:
23/7

3.2857142857142856

In [ ]:
23 % 7

2

In [ ]:
23 // 7

3

### Variables y tipos de datos

Python es un lenguaje de tipado dinámico en el que no hace falta declarar el tipo de dato que asignará a una variable,
de igual manera una variable puede cambiar de tipo conforme la ejecución del programa, por ello se debe tener cuidado
con la sintaxis para definir cada tipo de dato.

#### Variables

Las variables son referencias a los objetos de Python, son creadas por asignación mediante el signo `=`, por ejemplo:

In [ ]:
a = 6
a

6

In [ ]:
b = 3*a
b

18

## Ejemplo motivador con NumPy

Un maestro, curvando las calificaciones de las pruebas para dar cuenta de una prueba lamentablemente difícil.
La curva debería mejorar la calificación del estudiante en relación con el lugar donde terminaron con respecto al promedio del grupo.
Tampoco debería lastimar al estudiante al reducir su calificación, y no debería darle a nadie más del 100%.

[Basado en `curve_grades.ipynb`](https://github.com/realpython/materials/blob/master/numpy-tutorial/curve_grades.ipynb).

In [ ]:
import numpy as np

In [ ]:
type?

In [ ]:
lista = [[1, 2], [3, 4], [5, 6]]

In [ ]:
type(lista)

list

In [ ]:
A = np.array(lista)

In [ ]:
type(A)

numpy.ndarray

In [ ]:
np.clip?

In [ ]:
B = np.ones(10)

In [ ]:
np.shape(A)

(3, 2)

In [ ]:
np.shape(A.T)

(2, 3)

In [ ]:
CURVE_CENTER = 13

In [ ]:
def curve(grades):
    """Adjusts an array of grades so that the average is roughly shifted
    to the specified curve center.

    This will never cause a student's grade to decrease, and it will
    never cause the final grade to go over 100%.

    Parameters:
        grades (np.ndarray): The individual student grades, between 0 y 20.

    Returns:
        (np.ndarray): A new array of grades, adjusted upwards, but in
                      the same order.
    """
    average = grades.mean()
    change = CURVE_CENTER - average
    new_grades = grades + change
    return np.clip(new_grades, grades, 20)

In [ ]:
grades = np.array([[6, 8, 12, 5, 8, 11, 3, 10]])
curve(grades)

array([[11.125, 13.125, 17.125, 10.125, 13.125, 16.125,  8.125, 15.125]])

In [ ]:
np.swapaxes?

In [ ]:
np.clip?

In [ ]:
temperatures = np.array([
    29.3, 42.1, 18.8, 16.1, 38.0, 12.5,
    12.6, 49.9, 38.6, 31.3, 9.2, 22.2
]).reshape(2, 2, 3)

In [ ]:
temperatures

array([[[29.3, 42.1, 18.8],
        [16.1, 38. , 12.5]],

       [[12.6, 49.9, 38.6],
        [31.3,  9.2, 22.2]]])

In [ ]:
temperatures.shape

(2, 2, 3)

In [ ]:
temperatures

array([[[29.3, 42.1, 18.8],
        [16.1, 38. , 12.5]],

       [[12.6, 49.9, 38.6],
        [31.3,  9.2, 22.2]]])

In [ ]:
np.swapaxes(temperatures, 1, 2)

array([[[29.3, 16.1],
        [42.1, 38. ],
        [18.8, 12.5]],

       [[12.6, 31.3],
        [49.9,  9.2],
        [38.6, 22.2]]])

In [ ]:
temperatures.shape

(2, 2, 3)

In [ ]:
table = np.array([
    [5, 3, 7, 1],
    [2, 6, 7 ,9],
    [1, 1, 1, 1],
    [4, 3, 2, 0],
])

In [ ]:
table.max()

9

In [ ]:
table.max(axis=0)

array([5, 6, 7, 9])

In [ ]:
table.max(axis=1)

array([7, 9, 1, 4])

In [ ]:
np.linspace?

In [ ]:
np.arange(100).shape

(100,)

In [ ]:
# Estamos creando 4 capas y en cada una de ellas tenemos un vector de 8 entradas.
A = np.arange(32).reshape(1, 8, 4)

In [ ]:
A

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [ ]:
B = np.arange(48).reshape(1, 6, 8)

In [ ]:
# Broadcasting
A = np.ones(5) + np.pi

In [ ]:
A

array([4.14159265, 4.14159265, 4.14159265, 4.14159265, 4.14159265])

In [ ]:
B

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]]])

In [ ]:
A + B

array([[[ 0,  2,  4,  6,  8, 10, 12, 14],
        [ 8, 10, 12, 14, 16, 18, 20, 22],
        [16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54]],

       [[ 8, 10, 12, 14, 16, 18, 20, 22],
        [16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62]],

       [[16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62],
        [56, 58, 60, 62, 64, 66, 68, 70]],

       [[24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62],
        [56, 58, 60, 62, 64, 66, 68, 70],
        [64, 66, 68, 70, 72,

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
np.shape(A)

(3, 2)

In [ ]:
A @ A.T

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [ ]:
square = np.array([
    [16, 3, 2, 13],
    [5, 10, 11, 8],
    [9, 6, 7, 12],
    [4, 15, 14, 1]
])

In [ ]:
square

array([[16,  3,  2, 13],
       [ 5, 10, 11,  8],
       [ 9,  6,  7, 12],
       [ 4, 15, 14,  1]])

In [ ]:
assert 1 == 0

AssertionError: ignored

In [ ]:
square

array([[16,  3,  2, 13],
       [ 5, 10, 11,  8],
       [ 9,  6,  7, 12],
       [ 4, 15, 14,  1]])

In [ ]:
square[0, :].sum()

34

In [ ]:
for i in range(4):
  assert square[:, i].sum() == 34
  assert square[i, :].sum() == 34

In [ ]:
assert square[:2, :2].sum() == 34

In [ ]:
numbers = np.linspace(5, 50, 24, dtype=int).reshape(4, -1)

In [ ]:
numbers % 16 == 12

array([[False, False, False, False,  True, False],
       [False, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [False, False,  True, False, False, False]])

In [ ]:
mask = numbers % 4 == 0

In [ ]:
mask

array([[False, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

In [ ]:
numbers[mask]

array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [ ]:
by_four = numbers[numbers % 4 == 0]

In [ ]:
by_four

array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [ ]:
a = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
])

In [ ]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
data = np.array([
    [7, 1, 4],
    [8, 6, 5],
    [1, 2, 3]
])

In [ ]:
np.sort(data)

array([[1, 4, 7],
       [5, 6, 8],
       [1, 2, 3]])

In [ ]:
np.sort(data, axis=None)

array([1, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.sort(data, axis=0)

array([[1, 1, 3],
       [7, 2, 4],
       [8, 6, 5]])

## [Ejercicios](https://cpp-review-dune.github.io/python/ex1.pdf)