# PYTHON PARA INGENIERIA
## CTIC - UNI
### Profesor: Juan Luis Herencia Guerra
### EMail: jherenciag@uni.edu.pe

#### Estructura de datos en Python

In [1]:
# Listas
import numpy as np
L1 = [4, 5, 6, 9, 8, 7, 1]
L1

[4, 5, 6, 9, 8, 7, 1]

In [2]:
len(L1)

7

In [3]:
max(L1)

9

In [4]:
min(L1)

1

In [5]:
L1[3]

9

In [6]:
# Los indices comienzan en cero
L1[3] = 19
L1

[4, 5, 6, 19, 8, 7, 1]

In [7]:
# Obtener el ultimo elemento
L1[-1]

1

In [8]:
# saber el indice de 19
L1.index(19)

3

In [9]:
L2 = [[3, 5], 'Hola', 3, 3.14]
L2

[[3, 5], 'Hola', 3, 3.14]

In [10]:
L2[3]

3.14

In [11]:
for e in L2:
    print(e)

[3, 5]
Hola
3
3.14


In [12]:
# Arreglos
# Colección homogénea de datos (del mismo tipo de dato)
L1

[4, 5, 6, 19, 8, 7, 1]

In [13]:
# Arreglo unidimensional o vector
L1

[4, 5, 6, 19, 8, 7, 1]

In [14]:
# Arreglo bidimensional o matriz
fila1 = [4, 8, 6]
fila2 = [1, 5, 9]

In [15]:
# matriz de 2 filas x 3 columnas
matriz = [fila1, fila2]
matriz

[[4, 8, 6], [1, 5, 9]]

In [16]:
# Acceder al elemento 9
matriz[1]

[1, 5, 9]

In [17]:
# matriz[fila][columna]
matriz[1][2]

9

In [18]:
# Para acceder a la informacion
# Saber el elemento y su posicion (fila, columna)
matriz[0][1]

8

#### Numpy

In [19]:
# Es una libreria para análisis y procesamiento numérico
np.__version__

'1.24.1'

In [20]:
x = np.array([7, 5, 3, 6])
x

array([7, 5, 3, 6])

In [21]:
x ** 0.5

array([2.64575131, 2.23606798, 1.73205081, 2.44948974])

In [22]:
# Tipo de dato del arreglo
type(x)

numpy.ndarray

In [23]:
# Tipo de dato de cada elemento
x.dtype

dtype('int64')

In [24]:
# int8, int16, int32, ...

In [25]:
x.nbytes

32

#### Números Aleatorios

In [26]:
# Enteros
# np.random.randint(min,max)
# Generacion entre min y max - 1
np.random.randint(0, 10)

8

In [27]:
# simular 10 tiradas de un dado
np.random.randint(1, 7, 10)

array([4, 5, 4, 1, 3, 3, 4, 3, 6, 1])

In [28]:
# simular las calificaciones de 4 practicas para 15 alumnos
calif = np.random.randint(1, 21, (15, 4))
calif

array([[17, 13,  5,  1],
       [ 8, 11, 11,  4],
       [ 1, 19, 11,  9],
       [14, 11, 10, 13],
       [16, 16,  3, 17],
       [14, 10,  5,  6],
       [17, 20,  9, 13],
       [ 1,  6,  6, 17],
       [14,  3,  5,  4],
       [20,  6,  2, 20],
       [ 7,  4, 20, 11],
       [19,  8,  5,  2],
       [ 6,  2,  7,  9],
       [16,  9,  4, 14],
       [14,  9,  8,  6]])

In [29]:
np.sum(calif, axis=1) / 4

array([ 9.  ,  8.5 , 10.  , 12.  , 13.  ,  8.75, 14.75,  7.5 ,  6.5 ,
       12.  , 10.5 ,  8.5 ,  6.  , 10.75,  9.25])

In [30]:
# numero aleatorio real entre 0 y 1
np.random.rand()

0.49910272623578156

In [31]:
# numero aleatorio real entre 0 y 100
np.random.rand()*100

37.584781514228226